export const TIMEZONE_OPTIONS = [
  { value: "UTC", label: "UTC" },
  // North America
  { value: "America/New_York",    label: "Eastern Time (US & Canada)" },
  { value: "America/Chicago",     label: "Central Time (US & Canada)" },
  { value: "America/Denver",      label: "Mountain Time (US & Canada)" },
  { value: "America/Los_Angeles", label: "Pacific Time (US & Canada)" },
  { value: "America/Toronto",     label: "Eastern Time (Canada)" },
  { value: "America/Winnipeg",    label: "Central Time (Canada)" },
  { value: "America/Edmonton",    label: "Mountain Time (Canada)" },
  { value: "America/Vancouver",   label: "Pacific Time (Canada)" },
  { value: "America/Halifax",     label: "Atlantic Time (Canada)" },
  { value: "America/St_Johns",    label: "Newfoundland" },
  { value: "America/Anchorage",   label: "Alaska" },
  { value: "Pacific/Honolulu",    label: "Hawaii" },
  { value: "America/Mexico_City", label: "Mexico City" },
  // South America
  { value: "America/Sao_Paulo",                 label: "Brasilia" },
  { value: "America/Argentina/Buenos_Aires",    label: "Buenos Aires" },
  { value: "America/Santiago",                  label: "Santiago" },
  { value: "America/Bogota",                    label: "Bogota, Lima" },
  { value: "America/Caracas",                   label: "Caracas" },
  // Europe
  { value: "Europe/London",    label: "London" },
  { value: "Europe/Dublin",    label: "Dublin" },
  { value: "Europe/Lisbon",    label: "Lisbon" },
  { value: "Europe/Paris",     label: "Paris, Berlin, Amsterdam" },
  { value: "Europe/Rome",      label: "Rome, Stockholm, Vienna" },
  { value: "Europe/Warsaw",    label: "Warsaw, Prague" },
  { value: "Europe/Athens",    label: "Athens, Helsinki, Kyiv" },
  { value: "Europe/Istanbul",  label: "Istanbul" },
  { value: "Europe/Moscow",    label: "Moscow" },
  // Africa
  { value: "Africa/Cairo",         label: "Cairo" },
  { value: "Africa/Lagos",         label: "Lagos, Kinshasa" },
  { value: "Africa/Nairobi",       label: "Nairobi" },
  { value: "Africa/Johannesburg",  label: "Johannesburg" },
  // Asia
  { value: "Asia/Dubai",      label: "Dubai, Abu Dhabi" },
  { value: "Asia/Karachi",    label: "Karachi" },
  { value: "Asia/Kolkata",    label: "Mumbai, Kolkata, New Delhi" },
  { value: "Asia/Dhaka",      label: "Dhaka" },
  { value: "Asia/Bangkok",    label: "Bangkok, Jakarta" },
  { value: "Asia/Singapore",  label: "Singapore, Kuala Lumpur" },
  { value: "Asia/Shanghai",   label: "Beijing, Shanghai" },
  { value: "Asia/Hong_Kong",  label: "Hong Kong" },
  { value: "Asia/Tokyo",      label: "Tokyo" },
  { value: "Asia/Seoul",      label: "Seoul" },
  // Oceania
  { value: "Australia/Perth",    label: "Perth" },
  { value: "Australia/Adelaide", label: "Adelaide" },
  { value: "Australia/Sydney",   label: "Sydney, Melbourne" },
  { value: "Pacific/Auckland",   label: "Auckland" },
  { value: "Pacific/Fiji",       label: "Fiji" },
];
